# Generated by Django 4.1.6 on 2023-02-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('swordsmith', models.CharField(max_length=100)),
                ('blade_material', models.CharField(max_length=100)),
                ('blade_length', models.IntegerField()),
            ],
        ),
    ]
