# Generated by Django 4.1.6 on 2023-02-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sword',
            name='name',
        ),
        migrations.AlterField(
            model_name='sword',
            name='blade_length',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
