# Generated by Django 4.1.6 on 2023-02-08 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_sword_blade_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sword',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='sword',
            name='swordsmith',
        ),
        migrations.CreateModel(
            name='Swordsmith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('sword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sword')),
            ],
        ),
    ]
