# Generated by Django 4.1.6 on 2023-02-08 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_sword_origin_remove_sword_swordsmith_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swordsmith',
            name='sword',
        ),
        migrations.AddField(
            model_name='sword',
            name='sword',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.swordsmith'),
            preserve_default=False,
        ),
    ]
