# Generated by Django 4.1.6 on 2023-02-08 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_swordsmith_sword_sword_sword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sword',
            old_name='sword',
            new_name='swordsmith',
        ),
    ]
